// Dados de produtos
const produtos = [
	{
		id: 1,
		categoria: "Poesia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
        
	},
	{
		id: 2,
		categoria: "Poesia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
	{
		id: 3,
		categoria: "Poesia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
	{
		id: 4,
		categoria: "Poesia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
	{
		id: 5,
		categoria: "Filosofia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 6,
		categoria: "Brazil",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 7,
		categoria: "Brazil",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 8,
		categoria: "Sociologia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 9,
		categoria: "Sociologia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 10,
		categoria: "Geografia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 11,
		categoria: "Psicologia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	},
    {
		id: 12,
		categoria: "Antropologia",
		nome: "Smartphone",
		descricao:  "<p><b>O moço Loiro.</b> <br><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est.orem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue ante ut purus gravida ultricies. Nunc quis molestie nibh, sit amet sollicitudin nibh. Aliquam fringilla nisi nec nibh ornare volutpat in ac felis. Nullam id nulla tempus, finibus lacus at, gravida ipsum. Vestibulum vestibulum et lacus quis hendrerit. Nullam nisi dolor, suscipit ut commodo quis, volutpat eu purus. Nulla ac posuere libero, vel imperdiet est. <br><br> Data de publicação: <BR> Editora: <BR> Autor: <BR> Idioma: </p>",

		imagem: "/O Moço Loiro.jpeg"
	}
];

// Função para renderizar produtos
function renderizarProdutos(categoria) {
	const produtosContainer = document.querySelector(".produtos");
	produtosContainer.innerHTML = "";

	produtos.forEach((produto) => {
		if (produto.categoria === categoria) {
			const produtoHTML = `
				<div class="produto">
					<img src="${produto.imagem}" alt="${produto.nome}">
					
					<p>${produto.descricao}</p>
				</div>
			`;
			produtosContainer.insertAdjacentHTML("beforeend", produtoHTML);
		}
	});
}


// Função para lidar com o clique em uma categoria
function lidarComCliqueCategoria(event) {
	const categoria = event.target.dataset.categoria;
	renderizarProdutos(categoria);
}

// Adicionar evento de clique às categorias
const categorias = document.querySelectorAll(".categoria");
categorias.forEach((categoria) => {
	categoria.addEventListener("click", lidarComCliqueCategoria);
});

// Renderizar produtos da categoria "eletronicos" por padrão
renderizarProdutos("Poesia");
